general:
  productiveBranch: 'infrastructure-integration-test'
  collectTelemetryData: false
steps:
  cloudFoundryDeploy:
    dockerImage: localhost:5000/ppiper/cf-cli
  executeNpm:
    dockerImage: 's4sdk/docker-node-browsers:v15'
stages:
  npmAudit:
    auditedAdvisories:
      - "146"
      - "593"
      - "607"
      - "803"
      - "886"
  productionDeployment:
    cfTargets:
      - org: 'P2001099548trial_trial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'devops-docker-images-IT'
        manifest: 'manifest.yml'
        credentialsId: 'devops-docker-images-IT-cf'
    appUrls:
      - url: 'https://devops-docker-images-it.cfapps.eu10.hana.ondemand.com'
        credentialId: 'devops-docker-images-IT-cf'
