general:
  productiveBranch: 'infrastructure-integration-test'
  collectTelemetryData: false
steps:
  cloudFoundryDeploy:
    dockerImage: localhost:5000/ppiper/cf-cli
  executeNpm:
    dockerImage: 's4sdk/docker-node-browsers:v15'
stages:
  npmAudit:
    auditedAdvisories:
      - "146"
      - "593"
      - "607"
      - "803"
      - "886"
