general:
  productiveBranch: 'master'
  collectTelemetryData: false
steps:
  cloudFoundryDeploy:
    dockerImage: localhost:5000/ppiper/cf-cli
  executeNpm:
    dockerImage: 's4sdk/docker-node-browsers:v15'
  artifactPrepareVersion:
    versioningType: 'library'
stages:
  productionDeployment:
    cfTargets:
      - org: 'piper'
        space: 'infra-testing'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'devops-docker-images-IT'
        manifest: 'manifest.yml'
        credentialsId: 'devops-docker-images-IT-cf'
