general:
  productiveBranch: 'master'
  collectTelemetryData: false
steps:
  mtaBuild:
    dockerImage: localhost:5000/ppiper/mta-archive-builder
    mtaBuildTool: classic
  artifactPrepareVersion:
    versioningType: 'library'
