steps:
  cloudFoundryDeploy:
    apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
    deployTool: mtaDeployPlugin
    deployType: standard
    org: piper
    space: infra-testing
    appName: 'devops-docker-images-IT'
