name: Build and push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  consumer-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: consumer-test
    - name: Run CI
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        docker build -t ppiper/cloud-foundry-integration-test:maven .
        docker push ppiper/cloud-foundry-integration-test:maven

  mta-cf-integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: mta-cf-integration-test
    - name: Run CI
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        docker build -t ppiper/cloud-foundry-integration-test:mta .
        docker push ppiper/cloud-foundry-integration-test:mta
        
  validate-ts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: validate-ts
    - name: Run CI
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        docker build -t ppiper/cloud-foundry-integration-test:ts .
        docker push ppiper/cloud-foundry-integration-test:ts
